### ISSUE TITLE
Missing collection item in cache

### ISSUE THREAD

**Issue by rorocabrera** [metaplex-foundation/mpl-candy-machine#39]
have followed all steps in this guide https://docs.metaplex.com/developer-tools/sugar/tutorials/my-first-candy-machine

but get this error everytime  i run    sugar deploy

Error running command (re-run needed): Missing collection item in cache

this is what my config looks like :

![Screenshot from 2023-06-16 09-53-05](https://github.com/metaplex-foundation/mpl-candy-machine/assets/67237201/e551a11d-234e-4dc1-8153-5d60fba6f9dd)

in the cache file there are 6 items from 0 to 5 similar to what the example in the guide looks like.

Any ideas what can be happening? thanks

**Comment by samuelvanderwaal** [comment]
The link you posted is for Candy Machine V2, but Sugar creates Candy Machine V3 and your config is for CMV3. 

<img width="995" alt="Screenshot 2023-06-16 at 9 02 58 AM" src="https://github.com/metaplex-foundation/mpl-candy-machine/assets/1684605/03ee8552-e008-4d8b-b41d-dc52c6ba6207">

Click the link to go to the newer tutorial and follow that. It will explain that you need the collection NFT files in the assets directory as CMV3 requires mints to have collections associated with them. If you run into trouble with that, post on the Metaplex Discord: https://discord.gg/metaplex
