### ISSUE TITLE
Unable to use mpl-candy-machine in React

### ISSUE THREAD

**Issue by bircher044** [metaplex-foundation/mpl-candy-machine#63]
Hi!
I was hoping to make a feature for updating spl-token metadata on frontend. I'm using the latest version of packages. But as soon as i import them I start receiving this error:

Class extends value undefined is not a constructor or null
TypeError: Class extends value undefined is not a constructor or null

my imports:
```
import { percentAmount, generateSigner, signerIdentity, createSignerFromKeypair } from '@metaplex-foundation/umi';
import { createAndMint, TokenStandard } from '@metaplex-foundation/mpl-token-metadata';
import { createUmi } from '@metaplex-foundation/umi-bundle-defaults';
import { mplCandyMachine } from '@metaplex-foundation/mpl-candy-machine'; 
```

![image](https://github.com/metaplex-foundation/mpl-candy-machine/assets/95891690/7893597f-1fe4-46a1-ab8a-7098c63120eb)

Please let me know if it's possible to fix if someone knows. Thank you

**Comment by MarkSackerberg** [comment]
Hey,
you are probably missing some polyfills.
karanluke.x shared his solution here:  https://lace-argon-9f9.notion.site/React-Metaplex-Polyfills-error-a3f3acc8bf144064a4c2ca86080068e5
Mayb it helps you, too :)
