### ISSUE TITLE
Is it possible to set dynamic price for a candy machine?

### ISSUE THREAD

**Issue by kaiqiangh** [metaplex-foundation/mpl-candy-machine#64]
I plan to setup a candy machine to distribute NFTs, but for the setting of payment, I'd like to set a dynamic price (by fetching price via oracles or fetching a pool state). 

Is it possible to do? Thanks.

**Comment by MarkSackerberg** [comment]
Hey @kaiqiangh,
this is not possible with the default candy machine guards. You would have to write your own guard similar to the solPayment guard that fetches the price from an oracle

**Comment by kaiqiangh** [comment]
Thanks for your confirm. doing research on it~
