### ISSUE TITLE
Why do I keep failing to execute sugar withdraw? This is my candy machine id: J3RZuYxgsGeZmwqrafb9ghYDtmqXAMWz6DHDANxyDw7j

### ISSUE THREAD

**Issue by wanggang1997** [metaplex-foundation/mpl-candy-machine#66]
🛑 Error running command (re-run needed): unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds % sugar withdraw --candy-machine J3RZuYxgsGeZmwqrafb9ghYDtmqXAMWz6DHDANxyDw7j --keypair /Users/jiawababa/keys___/id.json
[1/2] 🖥  Initializing connection
▪▪▪▪▪ Connected

[2/2] 🏧 Retrieving funds

🛑 Error running command (re-run needed): unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds
 getRent % sugar withdraw --candy-machine J3RZuYxgsGeZmwqrafb9ghYDtmqXAMWz6DHDANxyDw7j --keypair /Users/jiawababa/keys___/id.json
[1/2] 🖥  Initializing connection
▪▪▪▪▪ Connected

[2/2] 🏧 Retrieving funds

🛑 Error running command (re-run needed): unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds
 getRent % sugar withdraw --candy-machine J3RZuYxgsGeZmwqrafb9ghYDtmqXAMWz6DHDANxyDw7j --keypair /Users/jiawababa/keys___/id.json
[1/2] 🖥  Initializing connection
▪▪▪▪▪ Connected

[2/2] 🏧 Retrieving funds

🛑 Error running command (re-run needed): unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds
 getRent %

**Comment by samuelvanderwaal** [comment]
> 🛑 Error running command (re-run needed): unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds % sugar withdraw --candy-machine J3RZuYxgsGeZmwqrafb9ghYDtmqXAMWz6DHDANxyDw7j --keypair /Users/jiawababa/keys___/id.json [1/2] 🖥 Initializing connection ▪▪▪▪▪ Connected
> 
> [2/2] 🏧 Retrieving funds
> 
> 🛑 Error running command (re-run needed): unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds getRent % sugar withdraw --candy-machine J3RZuYxgsGeZmwqrafb9ghYDtmqXAMWz6DHDANxyDw7j --keypair /Users/jiawababa/keys___/id.json [1/2] 🖥 Initializing connection ▪▪▪▪▪ Connected
> 
> [2/2] 🏧 Retrieving funds
> 
> 🛑 Error running command (re-run needed): unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds getRent % sugar withdraw --candy-machine J3RZuYxgsGeZmwqrafb9ghYDtmqXAMWz6DHDANxyDw7j --keypair /Users/jiawababa/keys___/id.json [1/2] 🖥 Initializing connection ▪▪▪▪▪ Connected
> 
> [2/2] 🏧 Retrieving funds
> 
> 🛑 Error running command (re-run needed): unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds getRent %

Solana network is very congested right now. Make sure you're using the latest version of Sugar which has priority fees added, which should help.
