### ISSUE TITLE
 I have a question. I used Sugar to deploy an NFT and the open-source Candy Machine v3 UI from GitHub, but Phantom always marks it as a malicious dApp. Why is that? There are no additional signatures or transfer operations throughout the process!

### ISSUE THREAD

**Issue by wanggang1997** [metaplex-foundation/mpl-candy-machine#67]
Does Phantom wallet no longer allow developers to build their own NFT mint dApps?

**Comment by MarkSackerberg** [comment]
They mark new websites as possibly malicious, yes. This is not related to candy machine, but a general thing though.
They allowlist your website though when writing the blowfish mail that is in the warning message.
