### ISSUE TITLE
Why is a standard Sugar-built dapp marked as malicious by phantom’s Blowfish.xyz?

### ISSUE THREAD

**Issue by wanggang1997** [metaplex-foundation/mpl-candy-machine#68]
Does phantom block all organizations or individual dapp developers who do not apply?

**Comment by MarkSackerberg** [comment]
Hey @wanggang1997 
This is not related to CM. Blowfish is marking new website / domains as potentially malicious by default.
Write them an email and usually your website is allow listed in the span of some hours.
